# Generated by Django 4.1.3 on 2023-10-06 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mapapp", "0003_message"),
    ]

    operations = [
        migrations.CreateModel(
            name="SimpleMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=100)),
                ("subject", models.CharField(blank=True, max_length=100, null=True)),
                ("data", models.CharField(max_length=172)),
            ],
        ),
    ]
