# Generated by Django 4.1.3 on 2023-10-07 18:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("mapapp", "0004_simplemessage"),
    ]

    operations = [
        migrations.RenameField(
            model_name="simplemessage", old_name="subject", new_name="message_text",
        ),
        migrations.RemoveField(model_name="simplemessage", name="data",),
        migrations.AddField(
            model_name="simplemessage",
            name="timestamp",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
