# Generated by Django 4.1.3 on 2023-10-10 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mapapp", "0005_rename_subject_simplemessage_message_text_and_more"),
    ]

    operations = [
        migrations.DeleteModel(name="SimpleMessage",),
    ]
