# Generated by Django 4.1.3 on 2023-10-19 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mapapp", "0006_delete_simplemessage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incidents",
            name="incident_number",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
