# Generated by Django 4.1.3 on 2023-11-07 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mapapp", "0007_alter_incidents_incident_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="VenueName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("address", models.CharField(blank=True, max_length=200)),
                ("city", models.CharField(blank=True, max_length=50)),
                ("state", models.CharField(blank=True, max_length=2)),
                ("capacity", models.PositiveIntegerField(default=0)),
                ("latitude", models.FloatField(blank=True, default=None, null=True)),
                ("longitude", models.FloatField(blank=True, default=None, null=True)),
            ],
        ),
    ]
