# Generated by Django 4.1.3 on 2023-10-10 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simplemessageapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="simplemessage", name="timestamp",),
        migrations.AlterField(
            model_name="simplemessage",
            name="username",
            field=models.CharField(max_length=100),
        ),
    ]
