# Generated by Django 4.1.3 on 2023-10-10 17:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("simplemessageapp", "0002_remove_simplemessage_timestamp_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="simplemessage",
            name="timestamp",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
