# Generated by Django 4.1.3 on 2023-10-14 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simplemessageapp", "0003_simplemessage_timestamp"),
    ]

    operations = [
        migrations.AddField(
            model_name="simplemessage",
            name="is_read",
            field=models.BooleanField(default=False),
        ),
    ]
