# Generated by Django 4.1.3 on 2023-10-16 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("simplemessageapp", "0004_simplemessage_is_read"),
    ]

    operations = [
        migrations.RemoveField(model_name="simplemessage", name="is_read",),
    ]
