# Generated by Django 4.1.3 on 2023-10-17 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simplemessageapp", "0005_remove_simplemessage_is_read"),
    ]

    operations = [
        migrations.AddField(
            model_name="simplemessage",
            name="is_read",
            field=models.BooleanField(default=False),
        ),
    ]
