# Generated by Django 4.2.5 on 2023-09-28 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Incidents",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("UUID", models.CharField(max_length=255, unique=True)),
                (
                    "UUID_Serial",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("incident_number", models.CharField(max_length=100)),
                ("first_name", models.CharField(blank=True, max_length=100, null=True)),
                ("last_name", models.CharField(blank=True, max_length=100, null=True)),
                ("seating", models.CharField(blank=True, max_length=100, null=True)),
                ("type_incident", models.CharField(max_length=100)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("unit_responding", models.CharField(blank=True, max_length=100)),
                ("response_timestamp", models.DateTimeField(blank=True, null=True)),
                ("on_location_time", models.DateTimeField(blank=True, null=True)),
                ("transport", models.BooleanField(default=False)),
                ("additional_resources", models.TextField(blank=True, null=True)),
                ("age", models.IntegerField(blank=True, null=True)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("Male", "Male"), ("Female", "Female")],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("injury", models.TextField(blank=True, null=True)),
                ("address", models.CharField(blank=True, max_length=200, null=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("state", models.CharField(blank=True, max_length=50, null=True)),
                ("contacts", models.CharField(blank=True, max_length=150, null=True)),
                ("zipcode", models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
